#!/usr/bin/env bash

set -e

# Migrate
./bin/console -e prod doctrine:database:create --no-interaction --if-not-exists
./bin/console -e prod doctrine:migration:migrate --no-interaction --all-or-nothing --allow-no-migration

# Clean caches
./bin/console -e prod cache:clear
